/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBlessingsRouteImport } from './routes/_authenticated/admin.blessings'
import { Route as ApiPublicBlessingsIdRejectRouteImport } from './routes/api/public/blessings/$id/reject'
import { Route as ApiPublicBlessingsIdApproveRouteImport } from './routes/api/public/blessings/$id/approve'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBlessingsRoute =
  AuthenticatedAdminBlessingsRouteImport.update({
    id: '/blessings',
    path: '/blessings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicBlessingsIdRejectRoute =
  ApiPublicBlessingsIdRejectRouteImport.update({
    id: '/api/public/blessings/$id/reject',
    path: '/api/public/blessings/$id/reject',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBlessingsIdApproveRoute =
  ApiPublicBlessingsIdApproveRouteImport.update({
    id: '/api/public/blessings/$id/approve',
    path: '/api/public/blessings/$id/approve',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/admin/blessings': typeof AuthenticatedAdminBlessingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/blessings/$id/approve': typeof ApiPublicBlessingsIdApproveRoute
  '/api/public/blessings/$id/reject': typeof ApiPublicBlessingsIdRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/blessings': typeof AuthenticatedAdminBlessingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/blessings/$id/approve': typeof ApiPublicBlessingsIdApproveRoute
  '/api/public/blessings/$id/reject': typeof ApiPublicBlessingsIdRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/admin/blessings': typeof AuthenticatedAdminBlessingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/blessings/$id/approve': typeof ApiPublicBlessingsIdApproveRoute
  '/api/public/blessings/$id/reject': typeof ApiPublicBlessingsIdRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/admin/blessings'
    | '/admin/'
    | '/api/public/blessings/$id/approve'
    | '/api/public/blessings/$id/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/blessings'
    | '/admin'
    | '/api/public/blessings/$id/approve'
    | '/api/public/blessings/$id/reject'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/admin/blessings'
    | '/_authenticated/admin/'
    | '/api/public/blessings/$id/approve'
    | '/api/public/blessings/$id/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicBlessingsIdApproveRoute: typeof ApiPublicBlessingsIdApproveRoute
  ApiPublicBlessingsIdRejectRoute: typeof ApiPublicBlessingsIdRejectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/blessings': {
      id: '/_authenticated/admin/blessings'
      path: '/blessings'
      fullPath: '/admin/blessings'
      preLoaderRoute: typeof AuthenticatedAdminBlessingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/blessings/$id/reject': {
      id: '/api/public/blessings/$id/reject'
      path: '/api/public/blessings/$id/reject'
      fullPath: '/api/public/blessings/$id/reject'
      preLoaderRoute: typeof ApiPublicBlessingsIdRejectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blessings/$id/approve': {
      id: '/api/public/blessings/$id/approve'
      path: '/api/public/blessings/$id/approve'
      fullPath: '/api/public/blessings/$id/approve'
      preLoaderRoute: typeof ApiPublicBlessingsIdApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBlessingsRoute: typeof AuthenticatedAdminBlessingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBlessingsRoute: AuthenticatedAdminBlessingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicBlessingsIdApproveRoute: ApiPublicBlessingsIdApproveRoute,
  ApiPublicBlessingsIdRejectRoute: ApiPublicBlessingsIdRejectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
